services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: voyagin
      POSTGRES_PASSWORD: voyagin
      POSTGRES_DB: voyagin
    ports:
      - "5432:5432"
    volumes:
      - voyagin-postgres-data:/var/lib/postgresql/data

volumes:
  voyagin-postgres-data:
